In [58]:
import pandas as pd

In [15]:
df=pd.read_excel(r"D:\Data_Analytics_Logesh\ML\ML_data.xlsx")

In [16]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
df.sample(5)

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
4,105,IT,55,39.0,4,3,Female,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,NaN,8,1,Male,Pass

In [18]:
df.head()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,NaN,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

In [21]:
X=df.drop("Final_Result",axis=1)
df

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,NaN,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

In [23]:
y=df["Final_Result"]
df

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,NaN,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

In [25]:
df.isnull()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False

In [28]:
df["Internal_Marks"]=df["Internal_Marks"].fillna(df['Internal_Marks'].mean())
df

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,62.5,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

In [30]:
df["Internal_Marks"]

0    78.0
1    45.0
2    88.0
3    62.5
4    39.0
Name: Internal_Marks, dtype: float64

In [38]:
df["Internal_Marks"]=df["Internal_Marks"].fillna(df['Internal_Marks'].median())
df

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result
0,101,CSE,85,78.0,12,0,Female,Pass
1,102,IT,62,45.0,5,2,Male,Fail
2,103,CSE,91,88.0,15,0,Female,Pass
3,104,ECE,74,62.5,8,1,Male,Pass
4,105,IT,55,39.0,4,3,Female,Fail

In [46]:

def LabelEncoder():
    ...

encoder=LabelEncoder()

In [52]:
df["Department"]

0    CSE
1     IT
2    CSE
3    ECE
4     IT
Name: Department, dtype: str

In [54]:
pd.get_dummies(df,columns=["Department"])

,Student_ID,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result,Department_CSE,Department_ECE,Department_IT
0,101,85,78.0,12,0,Female,Pass,True,False,False
1,102,62,45.0,5,2,Male,Fail,False,False,True
2,103,91,88.0,15,0,Female,Pass,True,False,False
3,104,74,62.5,8,1,Male,Pass,False,True,False
4,105,55,39.0,4,3,Female,Fail,False,False,True

In [61]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\ELCOT\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

In [63]:
from sklearn.preprocessing import MinMaxScaler

In [65]:
scaler = MinMaxScaler()

df["Study_Hours_scaled"] = scaler.fit_transform(
    df[["Study_Hours"]]
)

df.head()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result,Study_Hours_scaled
0,101,CSE,85,78.0,12,0,Female,Pass,0.727273
1,102,IT,62,45.0,5,2,Male,Fail,0.090909
2,103,CSE,91,88.0,15,0,Female,Pass,1.000000
3,104,ECE,74,62.5,8,1,Male,Pass,0.363636
4,105,IT,55,39.0,4,3,Female,Fail,0.000000

In [68]:
from sklearn.preprocessing import StandardScaler

In [70]:
std_scaler = StandardScaler()

df["Study_Hrs_std_scaled"] = std_scaler.fit_transform(
    df[["Study_Hours"]]
)

df.head()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result,Study_Hours_scaled,Study_Hrs_std_scaled
0,101,CSE,85,78.0,12,0,Female,Pass,0.727273,0.768025
1,102,IT,62,45.0,5,2,Male,Fail,0.090909,-0.912029
2,103,CSE,91,88.0,15,0,Female,Pass,1.000000,1.488048
3,104,ECE,74,62.5,8,1,Male,Pass,0.363636,-0.192006
4,105,IT,55,39.0,4,3,Female,Fail,0.000000,-1.152037

In [72]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

df["Study_Hrs_std_scaled"] = std_scaler.fit_transform(
    df[["Study_Hours"]]
)

df.head()

,Student_ID,Department,Attendance,Internal_Marks,Study_Hours,Backlogs,Gender,Final_Result,Study_Hours_scaled,Study_Hrs_std_scaled
0,101,CSE,85,78.0,12,0,Female,Pass,0.727273,0.768025
1,102,IT,62,45.0,5,2,Male,Fail,0.090909,-0.912029
2,103,CSE,91,88.0,15,0,Female,Pass,1.000000,1.488048
3,104,ECE,74,62.5,8,1,Male,Pass,0.363636,-0.192006
4,105,IT,55,39.0,4,3,Female,Fail,0.000000,-1.152037

In [74]:
std_scaler=StandardScaler()
df["Study_Hrs_std_scaled"]=std_scaler.fit_transform(df[['Study_Hours']])

In [77]:
import numpy as np

np.log1p([20000,22000,25000,30000,400000,50000])